require('user.plugins')
require('user.options')
require('user.bufferline')
require("user.telescope")
require("user.cmp")
require("user.comment")
require("user.toggleterm")
require('user.mappings')
require('user.colors')

